"""Core building blocks for MacClickPath."""

from .accessibility import get_accessibility_permission, open_accessibility_settings
from .coordinates import (
    DisplayInfo,
    Rect,
    SystemDesktopBackend,
    WindowInfo,
    preview_region,
    resolve_point,
    validate_action_target,
)
from .models import (
    ACTION_LABELS,
    AccessibilityPermission,
    AlwaysCondition,
    ExecutionState,
    MouseAction,
    MouseAtCondition,
    PixelColorCondition,
    Step,
    Workflow,
)
from .runner import (
    ActiveTimeBudget,
    CancellableActionExecutor,
    DirectActionExecutor,
    IsolatedActionExecutor,
    PausableClock,
    RunnerEvent,
    WorkflowRunner,
)
from .workflow import (
    CONDITION_LABELS,
    LABEL_CONDITIONS,
    evaluate_condition,
    load_workflow,
    save_workflow,
    validate_workflow,
    workflow_from_dict,
    workflow_to_dict,
    migrate_workflow_dict,
)
from .steps import (
    format_elapsed,
    perform_action,
    perform_step,
    validate_step_input,
    validate_step_sequence,
)

__all__ = [
    "ACTION_LABELS",
    "Rect",
    "DisplayInfo",
    "WindowInfo",
    "SystemDesktopBackend",
    "resolve_point",
    "validate_action_target",
    "preview_region",
    "AccessibilityPermission",
    "AlwaysCondition",
    "MouseAction",
    "MouseAtCondition",
    "PixelColorCondition",
    "ExecutionState",
    "Step",
    "Workflow",
    "ActiveTimeBudget",
    "CancellableActionExecutor",
    "DirectActionExecutor",
    "IsolatedActionExecutor",
    "PausableClock",
    "RunnerEvent",
    "WorkflowRunner",
    "CONDITION_LABELS",
    "LABEL_CONDITIONS",
    "evaluate_condition",
    "load_workflow",
    "save_workflow",
    "validate_workflow",
    "workflow_from_dict",
    "workflow_to_dict",
    "migrate_workflow_dict",
    "format_elapsed",
    "get_accessibility_permission",
    "open_accessibility_settings",
    "perform_action",
    "perform_step",
    "validate_step_input",
    "validate_step_sequence",
]
